### PR TITLE
Print pipe

### PR DESCRIPTION
**Pull request by fourstix**
Add function to print the settings command character pipe, by doubling the command character

### CODE REVIEW

**Comment by fourstix** [comment]
Sorry for the terse commit in the pull request.  This code adds logic to print a Pipe "|" character to the display.  The pipe character is used as the settings command and is currently eaten by the display.  Worse if the next character happens to collide with a command, that character will invoke a display setting rather than printing as a pipe.  With this change the user can escape the pipe character with two command settings characters, ie "||".  For example, "||-2|| = 2" would display on the serLCD as "|-2| = 2".
Closes #8

**Comment by fourstix** [comment]
I think I did the pull request wrong to this repository.  I have merged the commit to the master in my fork, and will create the pull request again from master to master.  I think that's the way it should be.

**Comment by fourstix** [comment]
Nevermind. I think I did it right.

**Comment by nseidle** [comment]
Hi @fourstix - this is awesome. Thanks for contributing! 

Issues are good, PRs are GOLD. But I couldn't respond because I've been exploring the caves of your xkcd link for the past three days.

This PR looks good. It looks like a dupe of PR #6. I'll close 6, and the original issue, then merge this one. 

Thank you again for your help!

**Pull request merged**
